### PR TITLE
Adds serialize and deserialize aliases.

### PR DESCRIPTION
**Pull request by radfahrer**

### CODE REVIEW

**Comment by tim** [comment]
@radfahrer What's the motivation/benefit of this? Any reason why you can't use load/dump?

**Comment by radfahrer** [comment]
Better naming, load/dump is confusing, serialize/deserialize is well
established.

**Comment by tim** [comment]
@radfahrer Better is subjective. If your preference is serialize/deserialize or encode/decode or format/parse or generate/parse or unparse/parse then you can always add aliases in your application. JSON and YAML both have load/dump, which AFAIK is an interface established by Ruby's Marshal. None of them support serialize/deserialize.

**Comment by radfahrer** [comment]
Load and dump don't convey any useful information. In your own
documentation, you use de/encode to explain load and dump,
"Use Rison.dump to encode Ruby objects as Rison, andRison.load to decode
Rison encoded strings into Ruby objects".  Why not accept more descriptive
aliases?

**Pull request closed without merging**
